### ISSUE TITLE
Can an agent access to chests?

### ISSUE THREAD

**Issue by phidnight** [minerllabs/minerl#104]
In ObtainIronPickaxe-v0, some demonstrations open a chest generated in a village or a pyramid.
Is it allowed for a MineRL agent to open and get items from a chest?
If allowed, could you tell me which action is corresponding to those?

**Comment by MadcowD** [comment]
In the main competition, the agent cannot access chests using the same interface. In fact the agent can destroy a chest to see its contents, but otherwise we have not enabled an action to remove from chests since this is so rare. 

When we release the Survival data from the dataset we will add a handler which enables this!

**Comment by Crissman** [comment]
See ObtainPickaxe task, r2g1common_fennel_genii-3_51968-54076.

**Comment by MadcowD** [comment]
@Crissman This is something we don't plan on supporting for the competition. It's an extremely small portion of the dataset. If we are able to get to it, we'll re-open this issue, but we're spread quite thin as it is. If anyone wants to try and implement this feature, please let us know!
