### ISSUE TITLE
Reward exceeds maximum score

### ISSUE THREAD

**Issue by keisuke-nakata** [minerllabs/minerl#135]
From the proposal paper, the maximum scores on Treechop/NavigateDense are 64 and 164.
But sometimes my agent obtained higher scores than maximum.

On Treechop, the agent could obtain 79 reward on this episode:
[openaigym.video.0.223.video000041.mp4.zip](https://github.com/minerllabs/minerl/files/3376965/openaigym.video.0.223.video000041.mp4.zip)

On NavigateDense, this episode shows 167 reward:
[openaigym.video.0.223.video000040.mp4.zip](https://github.com/minerllabs/minerl/files/3376968/openaigym.video.0.223.video000040.mp4.zip)

**Comment by MadcowD** [comment]
I believe the navigate reward is absolutely correct. I am investigating the treechop.

**Comment by marioyc** [comment]
is this solved for Treechop with this PR: https://github.com/minerllabs/minerl/pull/155 ?

**Comment by mattthelee** [comment]
I'm also seeing some strange scores, with some being between 64 and 164 for navigate dense task. As i understand it a score of 65-163 shouldn't be possible because it should jump from 64 to 164 when it finds the block, it isn't able to travel 65m closer to the block as it's only 64m away to begin with.
