### ISSUE TITLE
Chunk rendering issues

### ISSUE THREAD

**Issue by liquidnode** [minerllabs/minerl#150]
Sometimes a few chunks are not rendered by Minecraft. This happens in approx. 10% of episodes so this issue is not easy to reproduce. It is likely not an issue with the terrain generation as the collision with those unrendered chunks works. One can also see the outline of the selected yet invisible block. That means these chunks and their blocks exist, they are just not rendered. Instead of the unrendered chunks one sees the skybox behind them. Maybe it could be an issue with the occlusion culling (if Minecraft is using that) and/or it's a Minecraft bug and unrelated to the minerl package.

I'm running minerl version 0.2.0 on Windows 10. My CPU utilization is at 100% during my experiments (I'm training on my CPU), which also could be linked to this issue.

**Comment by liquidnode** [comment]
I tried to make a screenshot of this issue. Interestingly the unrendered chunks reappear if the minerl enviroment and python script is shutdown so that the Minecraft screen remains open.

**Comment by MadcowD** [comment]
This is actually a bug inherent to Minecraft, if you run Minecraft on a slow enough computer you can actually run into unloaded chunks. This is because chunk loading is asynchronous.

Likely what is happening is that because we are running the main MC thread so quickly the chunkloading thread fails to catch up in time. There is not a whole lot us mod developers can do about this, perhaps save for making chunk loading block the main thread.

I am going to close this for now until we get a better solution.
