### ISSUE TITLE
Training and rendering

### ISSUE THREAD

**Issue by rainbow979** [minerllabs/minerl#340]
Do it have to rendering when training? Does it take much more training time than normal gym environment?

**Comment by Miffyli** [comment]
Yes and yes. The rendering is required as this is how the agent will receive the image (and I the display window is required because of OpenGL requirements), and this does make MineRL/Minecraft a slower environment compared to e.g. Atari envs. 

But, on other hand, this encourages more sample efficient algorithms which could then be used in "real world" and robotics :)

**Comment by rainbow979** [comment]
OK. Thanks a lot.
