### ISSUE TITLE
Minecraft process psutil.Process(pid=20191, status='terminated') terminated with exit code 0 even though "done" condition is False

### ISSUE THREAD

**Issue by SaminYeasar** [minerllabs/minerl#346]
I'm getting an error where agent tries to perform env.step(action) I0627 14:33:59.522259 47430268073984 malmo.py:346] Minecraft process psutil.Process(pid=20191, status='terminated') terminated with exit code 0 I have checked the done condition which was still False. Running on Treechop and usually occurs after 100000 total timesteps

**Comment by Miffyli** [comment]
> usually occurs after 100000 total timesteps

Treechop should end much earlier (I think it was 8000 steps). There was a bug where episodes did not end in given timelimit, but that should be fixed. Try upgrading minerl with `pip install --upgrade minerl`. Also try uninstalling all previous versions with repeated `pip uninstall minerl` until no versions remain before re-installing it.

**Comment by SaminYeasar** [comment]
I think the problem I'm running into is different. I'm getting the status='terminated eariler. I'm ran the code on the latest version of minerl (0.3.5). I'm getting the error before it reaches 8000 episodic-steps and when the "done" is not yet met. And by "100000 total timesteps" I meant it usually occurs after 12 episodic run (8000 steps per episode)

**Comment by Miffyli** [comment]
Ah alright, sounds like a different bug. Do other scenarios work as expected, though? On our end, ObtainDiamondVectorObf-v0 environment is working as expected.

**Comment by SaminYeasar** [comment]
I will run the code on "ObtainDiamondVectorObf-v0" to check if the bug is due to any other system failure.

**Comment by MadcowD** [comment]
That "termination" message can be a few things.

1. your main python program closes
   * MineRL has a process watcher which checks to see if Minecraft is still running after the application which launches it closes (in this case it would be your training script). If The main application closes or dies somehow, the process watcher will kill the orphaned Minecraft instance and print to stdout that it has been terminated.
2. for some reason the socket between Minecraft and your main application (training script) closes or timesout. In this case, we have some fault tolerance and restart Minecraft (and hence the. termination message prints because its killing the old Minecraft process).

If it's 2, you should investigate if you're runing out of memory or if you're overloading your CPU (it can cause a pretty big slowdown and the socket will time out.) In general try and make your training script robust to env.step sometimes not working (and assume an episode end in that case).
