### ISSUE TITLE
Some samples show non-zero inventory on first tick

### ISSUE THREAD

**Issue by minerllabs** [minerllabs/minerl#41]
Some instances of `MineRLObtainDiamond-v0` show non-zero inventory for first time step where inventory should be empty

**Comment by brandonhoughton** [comment]
Items persist when doing back to back experiments ... unsure of the root cause. Data will be re-published using the current inventory container rather than the player's local inventory which looks to resolve issue. ETA +24-48hr for re-publishing data =( New download will be required unless a clean way to patch is implemented

**Comment by albert-yue** [comment]
Just wondering if this is resolved and we can redownload the data with the fix?

**Comment by minerllabs** [comment]
It has been resolved - will be published with an updated environment very soon!

**Comment by brandonhoughton** [comment]
Fixed with data version r2g1
