### ISSUE TITLE
Rendering screen is not appeared in MineRL 0.4.0 version

### ISSUE THREAD

**Issue by kimbring2** [minerllabs/minerl#573]
Hello,

I try to make a environment using below code.

`
import gym
`
`
import minerl
`
`
env = gym.make('MineRLNavigateDense-v0')
`

At this point, screen of game usually  was visualized. However, It does not show up at MineRL 0.4.0 version. Other version shows a screen after that code.

Should I add more code to see screen?

Thank you

**Comment by Miffyli** [comment]
In MineRL 0.4, the code adds a xvfb-run command when launching Minecraft, which hides the window. The next release and current `dev` branch has removed this code, so upon running the above code you will see the window again. *However*, due to other changes, the window does not update like it did with 0.3.7.

If you want to see the frames, I recommend using cv2 and its `imshow` function to see the image in real time.

**Comment by kimbring2** [comment]
@Miffyli Oh, I understand what you mean. Thank you for answer!
