### ISSUE TITLE
Is it possible to automatically enable the auto-jump feature?

### ISSUE THREAD

**Issue by wilson1yan** [minerllabs/minerl#630]

**Comment by Miffyli** [comment]
There is no function/API to do this, but you could modify the [options.txt](https://github.com/minerllabs/minerl/blob/dev/minerl/Malmo/Minecraft/run/options.txt) file to enable autojumping [here](https://github.com/minerllabs/minerl/blob/dev/minerl/Malmo/Minecraft/run/options.txt#L53) by changing that line to `autoJump:true`.

However, you might want to make sure this works first by (faster than `pip install`ing all the time. `-e` flag might not work):
1) installing MineRL with `pip install minerl`
2) navigating to the folder where MineRL is installed (the `site-packages` directory for Python).
3) navigate to `site-packages/minerl/minerl/Malmo/run`
4) modify options.txt in some obvious way
5) run MineRL to confirm the changes to options.txt are reflected

If above steps work, you might want to change the options.txt in the non-installed MineRL code, so that others installing from the same code will also have auto-jump enabled.

(Off-topic, but we are hoping to rerun the [BASALT](https://minerl.io/basalt/) competition this summer. Just bit of a heads up in case you want to work more on MineRL agents ;) )

**Comment by wilson1yan** [comment]
It works! Thanks!
