### ISSUE TITLE
error: subprocess-exited-with-error on windows 10

### ISSUE THREAD

**Issue by jakeyjr** [minerllabs/minerl#730]
[errors.txt](https://github.com/minerllabs/minerl/files/12266528/errors.txt)
sorry its so long it got cut off but what i ran was pip install git+https://github.com/minerllabs/minerl@v1.0.0
python: Python 3.10.11
ive been trying to do this for hours now and im struggling please help

**Comment by jakeyjr** [comment]
`PS C:\Users\baseball\Downloads\Video-Pre-Training-main\Video-Pre-Training-main> pip install --upgrade minerl
Collecting minerl
  Downloading minerl-0.4.4.tar.gz (70.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.1/70.1 MB 9.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting gym<0.20,>=0.13.1 (from minerl)
  Downloading gym-0.19.0.tar.gz (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 12.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in gym setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`
Also doesnt work when i upgrade

**Comment by Miffyli** [comment]
Try `pip install git+https://github.com/minerllabs/minerl` . Make sure to follow the pre-installation instructions [here](https://minerl.readthedocs.io/en/latest/tutorials/index.html) before you try installing it.

Installing `pip install minerl` will install v0.4.4. We have not updated the pypi with v1.0.0.

Installing `pip install pip install git+https://github.com/minerllabs/minerl@v1.0.0` fails as there is a bug in v1.0.0 version that now prevents its installation, but it is fixed in the newer versions.

You might want to contact the author of instructions you are following and suggest them to update the installation instructions with working version.

**Comment by jakeyjr** [comment]
i fixed it, i was using java 17 (outdated) instead of 8 and using the broken v1.0.0 version
