### ISSUE TITLE
How can I use ChatAction?

### ISSUE THREAD

**Issue by Zhoues** [minerllabs/minerl#747]
In the previous PR, I discovered that v1.0.0 could have ChatAction, which can be adapted to VPT. https://github.com/minerllabs/minerl/issues/676#issuecomment-1456362871

However, from the previous issue, I found that there are problems with v1.0.0.https://github.com/minerllabs/minerl/issues/726#issuecomment-1644788794

So what other ways can I use ChatAction?

**Comment by Miffyli** [comment]
Atm the chataction (due to bit of an oversight in that PR, as it was merged into wrong branch) is not in the newest `dev` branch which is a working v1.0.x version (and as you have noted, `v1.0.0` branch does not work). The best course of action would be to copy the things done in #638 to `dev`. I believe @KarolisRam  is working on this.

**Comment by Zhoues** [comment]
> Atm the chataction (due to bit of an oversight in that PR, as it was merged into wrong branch) is not in the newest `dev` branch which is a working v1.0.x version (and as you have noted, `v1.0.0` branch does not work). The best course of action would be to copy the things done in #638 to `dev`. I believe @KarolisRam is working on this.

I successfully add ChatAction to the `dev`.
Thanks a lot :)

**Comment by KarolisRam** [comment]
Yup, I was facing the same issue recently and did the changes of that PR here: https://github.com/KarolisRam/minerl. I'm using that repo to install MineRL for use with VPT. However, I'm not doing a PR to dev with that, because this breaks noops and possibly action sampling. Also we'd need to discuss which envs should have chat actions and which shouldn't. Don't have the bandwidth for that atm and don't want to risk breaking MineRL for others :)
