### ISSUE TITLE
How can I get a larger window

### ISSUE THREAD

**Issue by chenjunjie1994** [minerllabs/minerl#78]
Hi. I run the navigation demonstration program and get a extremely tiny window, in which I actually can see nothing. 
Is it running correctly ? Why is the window so small ? How can I make it larger ?

![1561096589(1)](https://user-images.githubusercontent.com/28914883/59901397-ac7fb300-942d-11e9-9def-649c529bee40.png)

**Comment by TimZF** [comment]
It is running correctly. It is so small because the observation is so small(64x64). I myself just showed the obs with cv2.imhsow then you can rescale it before you show it. Also Theres in this new window no distracting HUD elements.

`dObs = cv2.resize(obs["pov"],(100,100), interpolation=0)[::-1]`
`cv2.imshow("observation",dObs)`
`cv2.waitKey(1)`

Play around with interpolation and size and look what you like best.

**Comment by Mrugankakarte** [comment]
Just use `env.render()`in your code...a new window will pop up along with minecraft window, you can resize that window by dragging the corners.

**Comment by MadcowD** [comment]
env.render now works
